version: "3"

services:
  web:
    build: .
    container_name: "neotic-api"
    restart: always
    environment:
      - NODE_ENV=development
    command: ["/bin/sh", "-c", "sleep 4 && npm start"]
    volumes:
      - .:/usr/src/app/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "neotic-db"
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    command: mongod
